### ISSUE TITLE
Suggestion for createClass to Class transform

### ISSUE THREAD

**Issue by developit** [vutran/preact-codemod#1]
Hi @vutran!  This is a really awesome idea and I'd love to help push it even further!  I was playing around with the ASTExplorer copy linked in the Readme and came up with this alternative `createClass()` and `render()` transform that seems reasonably robust:

http://astexplorer.net/#/Pcp2Q5NFLq/7

It essentially transforms `createClass()` calls into ES Classes, which means they can be safely passed as JSX to `render()`.  The above implementation only has support for methods and properties on `createClass`, whereas a full version would need to know which properties passed to `createClass()` have to be converted to statics and which remain as property initializers on the resulting ES Class.

Let me know what you think!

**Comment by vutran** [comment]
@developit Thanks for feedback. I started this as an experiment to learn more about AST/codemods and glad that you found it.

Your ES class transforms looks a lot cleaner than what I had. I actually just pushed up an update which also preserved the JSX in the `render()` call and converted the `createClass` to a pure function. Your ES classes look a lot better. Did you want to submit a PR for this?

**Comment by developit** [comment]
Could do, though I think the pure function is a nicer approach.  I was thinking maybe the codemod could check if a `createClass()` component was pure or impure and choose the output type (pure function vs class) appropriately... should be as simple as checking for the existence of properties other than `render()`, `defaultProps` and `displayName`.

**Comment by vutran** [comment]
@developit I've just merged in this functionality based on your example with some minor adjustments which is moving the literals inside the ES6 constructor where necessary.

See here: https://astexplorer.net/#/M4CGKhVyp0

**Comment by developit** [comment]
@vutran looks good! How come you moved the literals into the constructor?  That's already how they work in ES6: https://goo.gl/imGiI5

Work either way though! One thing to watch out for: it might be worth passing `(props, context)` to `super()` so that `this.props` and `this.context` are defined in case they are referenced prior to the constructor being finished evaluation. (example: http://astexplorer.net/#/Pcp2Q5NFLq/11)

**Comment by vutran** [comment]
@developit Apologies been really busy at work and another app at the moment. I've just deployed the updated `constructor()` and `super()` calls.

**Comment by developit** [comment]
Awesome!
